apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-scheduler
  labels:
    app: random-scheduler
spec:
  selector:
    matchLabels:
      app: random-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: random-scheduler
    spec:
      serviceAccountName: test-sa
      containers:
      - name:  random-scheduler-pod
        image: docker.io/glarakis99/custom-k8s-scheduler:sample-ran
        imagePullPolicy: Always