apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-pod
  labels:
    app: random-pod
spec:
  selector:
    matchLabels:
      app: random-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: random-pod
    spec:
      schedulerName: my-scheduler
      containers:
      - name:  random-pod
        image: registry.k8s.io/pause:2.0
        imagePullPolicy: Always