---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: default
spec:
  ports:
  - name: padmin-port
    nodePort: 30165
    port: 80
    targetPort: 80
  selector:
    app: pgadmin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: user@e-mail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: password
        - name: PGADMIN_PORT
          value: "80"
        image: dpage/pgadmin4:8
        imagePullPolicy: IfNotPresent
        name: pgadmin
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisinsight
  name: redisinsight
  namespace: default
spec:
  ports:
  - name: redisinsight-port
    nodePort: 30170
    port: 5540
    targetPort: 5540
  selector:
    app: redisinsight
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
      - name: redisinsight
        image: redis/redisinsight:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5540